### ISSUE TITLE
The error of test the Dataloader

### ISSUE THREAD

**Issue by sysusicily** [mosaicml/llm-foundry#127]
when I run "python ../../llmfoundry/data/text_data.py --local_path ./my-copy-c4 --split val_small", I get the error
-------------------------------------------------------------
(mpt-env) root@autodl-container-645911b4fa-161dd8b6:~/autodl-tmp/llm-foundry/scripts/train# python ../../llmfoundry/data/text_data.py --local_path ./my-copy-c4 --split val_small

Traceback (most recent call last):
  File "../../llmfoundry/data/text_data.py", line 308, in <module>
    from llmfoundry.utils.builders import build_tokenizer
  File "/root/autodl-tmp/llm-foundry/llmfoundry/__init__.py", line 8, in <module>
    from llmfoundry.data import (ConcatTokensDataset,
  File "/root/autodl-tmp/llm-foundry/llmfoundry/data/__init__.py", line 4, in <module>
    from llmfoundry.data.datasets import ConcatTokensDataset, NoConcatDataset
  File "/root/autodl-tmp/llm-foundry/llmfoundry/data/datasets.py", line 9, in <module>
    import datasets as hf_datasets
  File "/root/autodl-tmp/llm-foundry/llmfoundry/data/datasets.py", line 15, in <module>
    class NoConcatDataset(IterableDataset):
  File "/root/autodl-tmp/llm-foundry/llmfoundry/data/datasets.py", line 22, in NoConcatDataset
    hf_datasets.Dataset]):
AttributeError: partially initialized module 'datasets' has no attribute 'Dataset' (most likely due to a circular import)

**Comment by tginart** [comment]
I ran into this as well. You can fix it by just getting rid of the typing hints. You'll probably run into more bugs after that though. Let me know how that goes.

**Comment by codestar12** [comment]
I'll take a look at this. Thanks for bringing it to our attention.

**Comment by hanlint** [comment]
Hello, we pushed a fix in #175 . Closing for now, please re-open if you run into the same issue again!
