### ISSUE TITLE
Adding alibi to mpt-7b_dolly_sft.yaml ?

### ISSUE THREAD

**Issue by tginart** [mosaicml/llm-foundry#133]
I'd like to try the mpt-7b_dolly_sft.yaml config with alibi. Is this supported with llm-foundry?

For this config edit to the model section:

> 
>   # Model
>   model:
>     name: hf_causal_lm
>     device: cpu
>     pretrained: true
>     pretrained_model_name_or_path: mosaicml/mpt-7b
>     config_overrides:
>       max_seq_len: ${max_seq_len}
>       attn_config:
>         attn_impl: triton
>       alibi: true

I get:

```
Traceback (most recent call last):
  File "/llm-foundry/scripts/train/train.py", line 254, in <module>
    main(cfg)
  File "/llm-foundry/scripts/train/train.py", line 144, in main
    model = build_composer_model(cfg.model, tokenizer)
  File "/llm-foundry/scripts/train/train.py", line 67, in build_composer_model
    return COMPOSER_MODEL_REGISTRY[model_cfg.name](model_cfg, tokenizer)
  File "/llm-foundry/llmfoundry/models/hf/hf_causal_lm.py", line 55, in __init__
    raise ValueError(
ValueError: config does not have attribute "alibi" to override (alibi: True).
```

**Comment by vchiley** [comment]
```
  # Model
  model:
    name: hf_causal_lm
    device: cpu
    pretrained: true
    pretrained_model_name_or_path: mosaicml/mpt-7b
    config_overrides:
      max_seq_len: ${max_seq_len}
      attn_config:
        attn_impl: triton
        alibi: true
```

`alibi: true` flag is an attn arg
