### ISSUE TITLE
Bug in convert_dataset_hf

### ISSUE THREAD

**Issue by eitanturok** [mosaicml/llm-foundry#1575]
I think the PR [Revert "Use utils to get shared fs safe signal file name](https://github.com/mosaicml/llm-foundry/pull/1389) broke the convert_dataset_hf.py script

On 4 GPUs, running
```
python scripts/data_prep/convert_dataset_hf.py --dataset allenai/c4 --data_subset en --out_root ./my-copy-c4 --splits train_small val_small --concat_tokens 2048 --tokenizer EleutherAI/gpt-neox-20b --eos_text '<|endoftext|>'
```
results in the error
```
Traceback (most recent call last):
  File "/root/tp/llm-foundry/scripts/train/../data_prep/convert_dataset_hf.py", line 51, in <module>
    convert_dataset_hf_from_args(
  File "/root/tp/llm-foundry/llmfoundry/command_utils/data_prep/convert_dataset_hf.py", line 476, in convert_dataset_hf_from_args
    convert_dataset_hf(
  File "/root/tp/llm-foundry/llmfoundry/command_utils/data_prep/convert_dataset_hf.py", line 343, in convert_dataset_hf
    built_tokenizer = build_tokenizer(tokenizer, tokenizer_kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tp/llm-foundry/llmfoundry/utils/builders.py", line 497, in build_tokenizer
    signal_file_path = dist.get_node_signal_file_name()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tp/composer/composer/utils/dist.py", line 641, in get_node_signal_file_name
    broadcast_object_list(file_name_list, src=0)
  File "/root/tp/composer/composer/utils/dist.py", line 407, in broadcast_object_list
    raise RuntimeError(
RuntimeError: The world_size(4) > 1, but the distributed package is not available or has not been initialized. Please check you have initialized the distributed runtime and that PyTorch has been built with distributed support. If calling this function outside Trainer, please ensure that `composer.utils.dist.initialize_dist` has been called first.
```

## To reproduce

1.
2.
3.

**Comment by xiaohanzhan-db** [comment]
Does it work if using composer as the launcher? 

composer -n 1 scripts/data_prep/convert_dataset_hf.py --dataset allenai/c4 --data_subset en --out_root ./my-copy-c4 --splits train_small val_small --concat_tokens 2048 --tokenizer EleutherAI/gpt-neox-20b --eos_text '<|endoftext|>'

**Comment by dakinggg** [comment]
@xiaohanzhan-db yes that also works. @eitanturok is putting in the script itself tho
