### ISSUE TITLE
xentropy_cuda_lib error

### ISSUE THREAD

**Issue by benam2** [mosaicml/llm-foundry#236]
Hi, I got an error which is related to the cuda. 
This is the version of cuda:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```
I did this:

`pip install xentropy-cuda-lib@git+https://github.com/HazyResearch/flash-attention.git@v0.2.8#subdirectory=csrc/xentropy`
But it did not fix the error. any idea how can I fix this? I'm trying to finetune Mpt-7b. Thanks for your help!
```
Initializing model...
Traceback (most recent call last):
  File "./Desktop/llm-foundry/llmfoundry/models/mpt/modeling_mpt.py", line 654, in __init__
    from flash_attn.losses.cross_entropy import CrossEntropyLoss as FusedCrossEntropyLoss  # type: ignore # isort: skip
  File "./.conda/envs/llm/lib/python3.9/site-packages/flash_attn/losses/cross_entropy.py", line 9, in <module>
    import xentropy_cuda_lib
ImportError: ./.conda/envs/llm/lib/python3.9/site-packages/xentropy_cuda_lib.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/llm-foundry/scripts/train/train.py", line 254, in <module>
    main(cfg)
  File "/llm-foundry/scripts/train/train.py", line 144, in main
    model = build_composer_model(cfg.model, tokenizer)
  File "/llm-foundry/scripts/train/train.py", line 67, in build_composer_model
    return COMPOSER_MODEL_REGISTRY[model_cfg.name](model_cfg, tokenizer)
  File "/llm-foundry/llmfoundry/models/mpt/modeling_mpt.py", line 659, in __init__
    raise ValueError(
ValueError: Fused Cross Entropy is not installed. Either (1) have a CUDA-compatible GPU and `pip install .[gpu]` if installing from source or `pip install xentropy-cuda-lib@git+https://github.com/HazyResearch/flash-attention.git@v0.2.8#subdirectory=csrc/xentropy` if installing from pypi, or (2) set your config model.loss_fn=torch_crossentropy.
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Global rank 0 (PID 31901) exited with code 1
ERROR:composer.cli.launcher:Global rank 0 (PID 31901) exited with code 
```

**Comment by vchiley** [comment]
Options:
1. setup llm-foundry using the setup instructions [here](https://github.com/mosaicml/llm-foundry#prerequisites)
2. or use torch impl of crossentropy (instead of using the `fused_crossentropy` impl; Note: `torch_crossentropy` is slightly slower)
```
model:
  loss_fn: torch_crossentropy
```

Our testing is done using composer pytorch img (as directed in our [setup instructions](https://github.com/mosaicml/llm-foundry#prerequisites)).
If you are having issues installing / using an outside library, issues should be reported to that library.
