### ISSUE TITLE
Training resorting to CPU despite having gpus

### ISSUE THREAD

**Issue by srivassid** [mosaicml/llm-foundry#313]
Hi

I have downloaded a docker image, and i am trying to train a model, but i am running into an issue. I get 2 warnings and 1 error. The first warning is

`UserWarning: FSDP is not applicable for single-GPU training. Reverting to DDP.`

Second warning is 

`UserWarning: Using `cfg.model.init_device='meta'` is only valid when using FSDP! Reverting to `cfg.model.init_device='cpu'`

and the error is 

`ValueError: Precision.AMP_BF16 is not supported for CPU training.`

I have 2 gpus, despite that the traning is resorting to CPU. Can anyone help?

Thanks

**Comment by abhi-mosaic** [comment]
Hi @srivassid , when you are attempting to run training, can you confirm that you are using the `composer train/train.py ...` command and not `python train/train.py ...`? This is a launcher script that will detect your N GPUs and launch N processes with the correct env vars.

You do not have to worry about the `cfg.model.init_device` device warnings, that is downstream of this.

If using `composer ...` doesn't solve the issue, could you share some more information about your system (what types of GPUs). Could you also confirm that if you open a python shell and type `>>> torch.cuda.device_count()`, you get `2`?

**Comment by srivassid** [comment]
Hi

Thanks for getting back to me

yes i am using composer. But when i run `torch.cuda.device_count()` i get 0, i have 3080ti. 

I tried to install nvidia drivers but couldn't. Can you tell me how can i resolve this?

Thanks

**Comment by ianpurton** [comment]
> I tried to install nvidia drivers but couldn't. Can you tell me how can i resolve this?

Do you mean the nvidia container runtime? https://github.com/NVIDIA/nvidia-container-runtime/

**Comment by srivassid** [comment]
But that is a separate image right?

**Comment by ianpurton** [comment]
No, the container runtime automagically puts the nvidia drivers into what ever image you are running when it sees the `--gpu all`.

**Comment by srivassid** [comment]
Hi @ianpurton 

Yes that worked. I can run train.py now. But i have a new problem. I get an out of memory error. 

`CUDA out of memory. Tried to allocate 3.07 GiB (GPU 1; 11.77 GiB total capacity; 9.44 GiB already allocated; 1.07 GiB free; 9.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Any ideas how to fix this? 

Thanks

**Comment by srivassid** [comment]
Hi @abhi-mosaic 

I tried to set it to auto and 4, but i got the following error

`/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
ERROR:composer.cli.launcher:Rank 0 crashed with exit code -7.`

What does it mean and how can i resolve this?

Thanks

**Comment by abhi-mosaic** [comment]
That `resource_tracker` error is a spurious thing from our StreamingDataset library, it should not cause any problems, it just throws a scary warning at the end of the script.

Were there any error logs above this line?

**Comment by abhi-mosaic** [comment]
Hi @srivassid , this is a torch2 + FSDP bug which we are fixing in the upcoming version of Composer.

For now, there are a couple workarounds mentioned in this thread here: https://github.com/mosaicml/llm-foundry/issues/221#issuecomment-1563657307

**Comment by srivassid** [comment]
Hi @abhi-mosaic 

I tried one of the workarounds and now i am facing a new issue

```
2023-06-13 06:22:04,353: rank0[708][MainThread]: DEBUG: composer.utils.checkpoint: Saving checkpoint to mpt-125m/ep{epoch}-ba{batch}-rank{rank}.pt
Traceback (most recent call last):
  File "/docker/mnt/llm-foundry/scripts/train/train.py", line 260, in <module>
    main(cfg)
  File "/docker/mnt/llm-foundry/scripts/train/train.py", line 249, in main
    trainer.fit()
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 1796, in fit
    self._train_loop()
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 2027, in _train_loop
    self.engine.run_event(Event.BATCH_CHECKPOINT)
  File "/usr/lib/python3/dist-packages/composer/core/engine.py", line 293, in run_event
    self._run_nonlogger_callbacks(event)
  File "/usr/lib/python3/dist-packages/composer/core/engine.py", line 475, in _run_nonlogger_callbacks
    self._run_callbacks(event, callbacks)
  File "/usr/lib/python3/dist-packages/composer/core/engine.py", line 467, in _run_callbacks
    cb.run_event(event, self.state, self.logger)
  File "/usr/lib/python3/dist-packages/composer/core/callback.py", line 96, in run_event
    return event_cb(state, logger)
  File "/usr/lib/python3/dist-packages/composer/callbacks/checkpoint_saver.py", line 346, in batch_checkpoint
    self._save_checkpoint(
  File "/usr/lib/python3/dist-packages/composer/callbacks/checkpoint_saver.py", line 400, in _save_checkpoint
    os.symlink(os.path.relpath(saved_path, os.path.dirname(symlink)), symlink)
PermissionError: [Errno 1] Operation not permitted: 'ep0-ba10-rank0.pt' -> 'mpt-125m/latest-rank0.pt'
2023-06-13 06:22:57,238: rank0[708][MainThread]: DEBUG: composer.core.engine: Closing the engine
2023-06-13 06:22:57,239: rank0[708][MainThread]: DEBUG: composer.core.engine: Closing callback ConsoleLogger
2023-06-13 06:22:57,240: rank0[708][MainThread]: DEBUG: composer.core.engine: Closing callback SpeedMonitor
2023-06-13 06:22:57,241: rank0[708][MainThread]: DEBUG: composer.core.engine: Closing callback LRMonitor
2023-06-13 06:22:57,241: rank0[708][MainThread]: DEBUG: composer.core.engine: Closing callback MemoryMonitor
2023-06-13 06:22:57,242: rank0[708][MainThread]: DEBUG: composer.core.engine: Closing callback RuntimeEstimator
2023-06-13 06:22:57,242: rank0[708][MainThread]: DEBUG: composer.core.engine: Closing callback CheckpointSaver
2023-06-13 06:22:57,243: rank0[708][MainThread]: DEBUG: composer.core.engine: Post-closing callback ConsoleLogger
2023-06-13 06:22:57,244: rank0[708][MainThread]: DEBUG: composer.core.engine: Post-closing callback SpeedMonitor
2023-06-13 06:22:57,244: rank0[708][MainThread]: DEBUG: composer.core.engine: Post-closing callback LRMonitor
2023-06-13 06:22:57,245: rank0[708][MainThread]: DEBUG: composer.core.engine: Post-closing callback MemoryMonitor
2023-06-13 06:22:57,246: rank0[708][MainThread]: DEBUG: composer.core.engine: Post-closing callback RuntimeEstimator
2023-06-13 06:22:57,246: rank0[708][MainThread]: DEBUG: composer.core.engine: Post-closing callback CheckpointSaver
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Global rank 0 (PID 708) exited with code 1
ERROR:composer.cli.launcher:Global rank 0 (PID 708) exited with code 1
```

I already gave write permission to train.py and ran the command with sudo. Can you help me out?

Thanks

**Comment by alextrott16** [comment]
For the sake of keeping the issues consistent with their titles, and since it sounds like the original issue has been addressed, I'm going to close this.

@srivassid if you're still running into checkpointing issues, could you please open up a new github issue directed at that.
