### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by GZL11** [mosaicml/llm-foundry#474]
## ❓ Question

Some errors have occurred when I use MPT-30B. The error code section is below:
```
trainer = Seq2SeqTrainer(
        model=model,
        tokenizer=tokenizer,
        args=training_args,
        **{k:v for k,v in data_module.items() if k != 'predict_dataset'},    # train_dataset, eval_dataset, datacollator
    )
trainer.train()
```
The information about error is below:
```
Traceback (most recent call last):
  File "/home/ksyer_/DB-GPT-Hub/src/train/train_qlora2.py", line 883, in <module>
    train()
  File "/home/ksyer_/DB-GPT-Hub/src/train/train_qlora2.py", line 845, in train
    train_result = trainer.train()
  File "/home/ksyer_/.conda/envs/new/lib/python3.9/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/home/ksyer_/.conda/envs/new/lib/python3.9/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/ksyer_/.conda/envs/new/lib/python3.9/site-packages/transformers/trainer.py", line 2699, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/ksyer_/.conda/envs/new/lib/python3.9/site-packages/transformers/trainer.py", line 2731, in compute_loss
    outputs = model(**inputs)  inputs: dict_keys(['input_ids', 'attention_mask', 'labels'])
  File "/home/ksyer_/.conda/envs/new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ksyer_/.conda/envs/new/lib/python3.9/site-packages/peft/peft_model.py", line 912, in forward
    return self.base_model(
  File "/home/ksyer_/.conda/envs/new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ksyer_/.conda/envs/new/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ksyer_/.cache/huggingface/modules/transformers_modules/modeling_mpt.py", line 271, in forward
    logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), True)
  File "/home/ksyer_/.conda/envs/new/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
```

**Comment by ramkrithik** [comment]
Same issue happened, when I tried fine tuning mpt-30b model using accelerate with deepspeed.

**Comment by dakinggg** [comment]
Closing as we don't plan on making any more MPT modifications with respect to hugging face trainer compatibility.
