### ISSUE TITLE
Fused Cross Entropy is not installed. Either (1) have a CUDA-compatible GPU and `pip install .[gpu]`, or (2) set your config model.loss_fn=torch_crossentropy.

### ISSUE THREAD

**Issue by Stanlito-AI** [mosaicml/llm-foundry#62]
Initializing model...
Traceback (most recent call last):
  File "/content/llm-foundry/llmfoundry/models/mpt/modeling_mpt.py", line 619, in __init__
    from flash_attn.losses.cross_entropy import CrossEntropyLoss as FusedCrossEntropyLoss  # type: ignore # isort: skip
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/losses/cross_entropy.py", line 9, in <module>
    import xentropy_cuda_lib
ImportError: /usr/local/lib/python3.10/dist-packages/xentropy_cuda_lib.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/llm-foundry/scripts/train/train.py", line 254, in <module>
    main(cfg)
  File "/content/llm-foundry/scripts/train/train.py", line 144, in main
    model = build_composer_model(cfg.model, tokenizer)
  File "/content/llm-foundry/scripts/train/train.py", line 67, in build_composer_model
    return COMPOSER_MODEL_REGISTRY[model_cfg.name](model_cfg, tokenizer)
  File "/content/llm-foundry/llmfoundry/models/mpt/modeling_mpt.py", line 624, in __init__
    raise ValueError(
ValueError: Fused Cross Entropy is not installed. Either (1) have a CUDA-compatible GPU and `pip install .[gpu]`, or (2) set your config model.loss_fn=torch_crossentropy.
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Global rank 0 (PID 13871) exited with code 1
ERROR:composer.cli.launcher:Global rank 0 (PID 13871) exited with code 1

**Comment by vchiley** [comment]
It looks like you didn't install all the requirements (`pip install .[gpu]` from the top level dir).

**Comment by Stanlito-AI** [comment]
(pip install .[gpu] thats the command i ran

**Comment by datafranch** [comment]
I am seeing the exact same issue, and I did install with `pip install .[gpu]`. My torch version is also 1.13.1, I have a venv specifically for this project.

**Comment by Einengutenmorgen** [comment]
Im having the same issue. Im using the docker image [2.0.1_cu117-python3.10-ubuntu20.04-aws] and don't use a Venv.

**Comment by Stanlito-AI** [comment]
> Im having the same issue. Im using the docker image [2.0.1_cu117-python3.10-ubuntu20.04-aws] and don't use a Venv. I can run the hf_ generate.py but I can't run train.py

Use the recommended docker image

**Comment by Einengutenmorgen** [comment]
thanks my mistake
