### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ighodgao** [mosaicml/llm-foundry#81]
Cannot run `python data_prep/convert_dataset_hf.py   --dataset c4 --data_subset en   --out_root my-copy-c4 --splits train_small val_small   --concat_tokens 2048 --tokenizer EleutherAI/gpt-neox-20b --eos_text '<|endoftext|>'`

Getting `Traceback (most recent call last):
  File "/home/ighodgao/llm-foundry/scripts/data_prep/convert_dataset_hf.py", line 14, in <module>
    from streaming import MDSWriter
ModuleNotFoundError: No module named 'streaming'`

`pip3 install streaming` returns a `ModuleNotFound` error for Cython, which I then install manually but then am not able to install streaming due to more installation problems..

I am in a python venv and have installed requirements already as outlined in the docs.

**Comment by samhavens** [comment]
The name when installing is different than importing,

`pip install mosaicml-streaming`

**Comment by ighodgao** [comment]
thanks!!

**Comment by vchiley** [comment]
I'd recommend installing all requirements: https://github.com/mosaicml/llm-foundry/issues/62#issuecomment-1538604986

**Comment by ighodgao** [comment]
I did install all requirements as specified there and on the Quickstart previously.

After` pip install mosaicml-streaming` I still can't run the data prep script:
```

(lfvenv) ighodgao@isha-determined:~/llm-foundry/scripts$ python data_prep/convert_dataset_hf.py \
  --dataset c4 --data_subset en \
  --out_root my-copy-c4 --splits train_small val_small \
  --concat_tokens 2048 --tokenizer EleutherAI/gpt-neox-20b --eos_text '<|endoftext|>'
Traceback (most recent call last):
  File "/home/ighodgao/llm-foundry/scripts/data_prep/convert_dataset_hf.py", line 19, in <module>
    from llmfoundry.data.datasets import ConcatTokensDataset, NoConcatDataset
ModuleNotFoundError: No module named 'llmfoundry'
```
