### ISSUE TITLE
HF Auth Token issue

### ISSUE THREAD

**Issue by ighodgao** [mosaicml/llm-foundry#83]
running
`python inference/hf_generate.py   --name_or_path mpt-125m-hf   --max_new_tokens 256   --prompts     "The answer to life, the universe, and happiness is"     "Here's a quick recipe for baking chocolate chip cookies: Start by"`

with all requirements installed 
gives 

```
Loading HF Config...
Traceback (most recent call last):
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/mpt-125m-hf/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-645aab74-09aa00034330c99310638c3a)

Repository Not Found for url: https://huggingface.co/mpt-125m-hf/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ighodgao/llm-foundry/scripts/inference/hf_generate.py", line 123, in main
    config = AutoConfig.from_pretrained(args.name_or_path,
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 916, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/ighodgao/llm-foundry/lfvenv/lib/python3.10/site-packages/transformers/utils/hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: mpt-125m-hf is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ighodgao/llm-foundry/scripts/inference/hf_generate.py", line 271, in <module>
    main(parse_args())
  File "/home/ighodgao/llm-foundry/scripts/inference/hf_generate.py", line 131, in main
    raise RuntimeError(
RuntimeError: If you are having auth problems, try logging in via `huggingface-cli login` or by setting the environment variable `export HUGGING_FACE_HUB_TOKEN=... using your access token from https://huggingface.co/settings/tokens.
```

I have already tried both methods suggested (logging in with cli was successful, and env variable is already set to the same write auth token)

**Comment by abhi-mosaic** [comment]
Hi @ighodgao , the command you are running is referencing a local HF folder `--name_or_path mpt-125m-hf`. Have you trained a model and converted to a HF checkpoint at that location?

If you are trying to point at a model on the HF Hub, you can replace that name with something like `--name_or_path mosaicml/mpt-7b` or `--name_or_path gpt2`. There is no need for an auth token unless pointing at a private model on the HF Hub.

**Comment by ighodgao** [comment]
No, I have not trained a model and converted it to a checkpoint at that location - was just following the Quickstart. Thanks for explaining how to point to a Hub model!

Seems to be downloading the model from Hub now so I'll close this issue if all goes well.

**Comment by ighodgao** [comment]
Are there any specific memory requirements for running inference on the trained models from HF Hub? I have an RTX 3050 but mpt-7b causes a crash

**Comment by samhavens** [comment]
@ighodgao I believe that is an 8GB card. You would need 8bit quantization to fit the model on that card, and even then, you would not have much space left for activations. 

Someone else in the community got `device_map='auto'` working [here](https://colab.research.google.com/gist/pszemraj/a979cdcc02edb916661c5dd97cf2294e/mpt-storywriter-sharded-inference.ipynb), which might work for you!
