### ISSUE TITLE
`ValueError` when following finetuning `mpt-7b-arc-easy--gpu.yaml` example with different default batch size

### ISSUE THREAD

**Issue by ouhenio** [mosaicml/llm-foundry#947]
## Environment
I'm trying to finetune a custom 7B-MPT, so I followed [this example](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/finetune_example/mpt-7b-arc-easy--gpu.yaml) which works flawlesly with my own model and datset.

Since I have enough compute power to use a bigger batch size, I increased it but got the following error:

```bash
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ouhenio/miniconda3/envs/mpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 748, in convert_to_tensors
    tensor = as_tensor(value)
  File "/home/ouhenio/miniconda3/envs/mpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 720, in as_tensor
    return torch.tensor(value)
ValueError: expected sequence of length 990 at dim 1 (got 974)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ouhenio/miniconda3/envs/mpt/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ouhenio/miniconda3/envs/mpt/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/ouhenio/mpt/llm-foundry/llmfoundry/data/finetuning/collator.py", line 116, in __call__
    batch = self._process_and_batch_decoder_only(examples)
  File "/home/ouhenio/fmpt/llm-foundry/llmfoundry/data/finetuning/collator.py", line 222, in _process_and_batch_decoder_only
    batch = self.tokenizer.pad(
  File "/home/ouhenio/miniconda3/envs/mpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3300, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/home/ouhenio/miniconda3/envs/mpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 223, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/home/ouhenio/miniconda3/envs/mpt/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 764, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same 
length. Perhaps your features (`token_type_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
```

## To reproduce

Here is my configuration yaml

```yaml
max_seq_len: 1024
global_seed: 14

# Run Name
run_name:  # If left blank, will be read from env var $COMPOSER_RUN_NAME

# Model
model:
  name: hf_causal_lm
  # init_device: meta
  pretrained_model_name_or_path: ./path_to_my_mpt
  pretrained: true  # false: only use the architecture; true: initialize with pretrained weights
  config_overrides:
    max_seq_len: ${max_seq_len}
    attn_config:
      attn_impl: triton
      # Set this to `true` if using `train_loader.dataset.packing_ratio` below
      attn_uses_sequence_id: false

# Tokenizer
tokenizer:
  name: ./path_to_my_mpt
  kwargs:
    model_max_length: ${max_seq_len}
    eos_token: <|endoftext|>

# Dataloaders
train_loader:
  name: finetuning
  dataset:
    ############
    # hf_name: json
    hf_name: pubmed_qa
    hf_kwargs:
      # Note: absolute paths for data_dir are more reliable;
      # relative paths will be interpreted relative to whatever your
      # working directory is when you run `train.py`
      # data_dir: ./qa_dataset/train
      name: pqa_artificial
    # Note: `scripts/train` will be the working directory when resolving
    # the preprocessing_fn import path
    preprocessing_fn: preprocessing:qa
    split: train
    ############
    shuffle: true
    max_seq_len: ${max_seq_len}
    # # Use packing_ratio: 'auto' to automatically profile and select the highest observed packing ratio with
    # # zero waste. In practice, this may result in > 0 waste because profiling is done on only a portion
    # # of the dataset.
    # # Or use `python llmfoundry/scripts/misc/profile_packing.py --yaml-path /path/to/this/yaml/ ...`
    # # to profile this run's optimal packing_ratio as it depends on GPU count,
    # # batch size, sequence length
    # packing_ratio:
  drop_last: true
  num_workers: 8

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 6.0e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 1ep
eval_interval: 1
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: 64

# System
seed: ${global_seed}
device_eval_batch_size: 1
device_train_microbatch_size: 8
# device_train_microbatch_size: auto
precision: amp_bf16

# FSDPj
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

# loggers:
#   wandb: {}

# Checkpoint to local filesystem or remote object store
# save_interval: 500ba
# save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
# save_folder: ./{run_name}/checkpoints
# save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints

# Load from local filesystem or remote object store
# load_path: ./gpt-125m/checkpoints/latest-rank{rank}.pt
# load_path: s3://my-bucket/my-folder/gpt-125m/checkpoints/latest-rank{rank}.pt
```
## Expected behavior

Training should go smoothly.

**Comment by dakinggg** [comment]
It looks like your tokenizer is producing `token_type_ids`, which it is not supposed to. This is generally specified on the tokenizer class (https://github.com/huggingface/transformers/blob/06901162b53918c302306b65b90c6a8ec99e0d0b/src/transformers/models/llama/tokenization_llama.py#L139), but the default is to include it (https://github.com/huggingface/transformers/blob/06901162b53918c302306b65b90c6a8ec99e0d0b/src/transformers/tokenization_utils_base.py#L1559). If you want to specify not to include it at run time, you can override with kwargs like so
```
tokenizer:
  kwargs:
    model_input_names:
      - input_ids
      - attention_mask
```

**Comment by ouhenio** [comment]
It worked! Thanks Daniel. :blush:
